
#include "GPUData.cginc"

// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Force
#pragma kernel Intergration


RWStructuredBuffer<ParticleData> _ParticlesDataBufferRead;
RWStructuredBuffer<ParticleData> _ParticlesDataBufferWrite;

[numthreads(8,8,1)]
void Force (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

}

[numthreads(8, 8, 1)]
void Intergration(uint3 id : SV_DispatchThreadID)
{
	// TODO: insert actual code here!

}
